{{ if eq .Values.receiving true }}
apiVersion: gateway.kyma-project.io/v1alpha2
kind: Api
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ include "github-connector-chart.name" . }}
    chart: {{ include "github-connector-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
    service:
      name: {{ .Release.Name }}
      port: {{ .Values.service.port }}
    hostname: {{ .Release.Name }}.{{ .Values.kymaAddress }}
{{ end }}