replicaCount: 1

container:
  containerPort: 8080
  limits:
    memory: "128Mi"
    cpu: "500m"

image: kymaflyingseals/github-connector:0.3.6

service:
  port: 80

githubToken: sampleToken
kymaAddress: kyma.address.com
githubEndpoint: 
  - repos/example/test
