apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "github-issue-sentiment-analysis.repository" . }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "github-issue-sentiment-analysis.repository" . }}-reader
rules:
- apiGroups: ["servicecatalog.k8s.io"]
  resources: ["serviceclasses", "serviceinstances", "servicebindings"]
  verbs: ["list", "create", "delete"]
- apiGroups: ["kubeless.io"]
  resources: ["functions"]
  verbs: ["create", "delete"]
- apiGroups: ["servicecatalog.kyma-project.io"]
  resources: ["servicebindingusages"]
  verbs: ["create", "delete"]
- apiGroups: ["eventing.kyma-project.io"]
  resources: ["subscriptions"]
  verbs: ["create", "delete"]


---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
subjects:
- kind: ServiceAccount
  name: {{ include "github-issue-sentiment-analysis.repository" . }}
roleRef:
  kind: Role
  name: {{ include "github-issue-sentiment-analysis.repository" . }}-reader
  apiGroup: rbac.authorization.k8s.io
