replicaCount: 1

image: kymaflyingseals/slack-connector:0.2.0
container:
  containerPort: 8080
  limits:
    memory: "128Mi"
    cpu: "100m"

service:
  port: 80

kymaAddress: adress
slackBotToken: token
workspaceName: name
slackSecret: secret

receiving: true
sending: true