apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-connector
spec:
  selector:
    matchLabels:
      app: github-connector
  template:
    metadata:
      labels:
        app: github-connector
    spec:
      containers:
      - name: github-connector
        image: karoljaksik/webhook-test:1.0.3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: GITHUB-SECRET
          value: "my-secret-key"
---
kind: Service
apiVersion: v1
metadata:
  name: github-connector-service
  labels:
    app: github-connector
spec:
  selector:
    app: github-connector
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
