apiVersion: batch/v1
kind: Job
metadata:
  name: github-slack-connectors-{{ include "azure-comments-analytics.repository" . }}
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: github-slack-connectors-{{ include "azure-comments-analytics.repository" . }}
        image: {{ .Values.image }}
        env: 
        - name: GITHUB_REPO
          value: {{ include "azure-comments-analytics.repository" . }}
        - name: SLACK_WORKSPACE
          value: {{ include "azure-comments-analytics.workspace" . }}
        - name: NAMESPACE
          value: {{ .Release.Namespace }}
        - name: CHANNEL_NAME
          value: {{ .Values.channelName }}
      serviceAccountName: {{ include "azure-comments-analytics.repository" . }}
      restartPolicy: Never
  backoffLimit: 0
